### ISSUE TITLE
install_labels is called before app is initialized

### ISSUE THREAD

**Issue by Pawamoy** [robinedwards/django-neomodel#1]
It seems that defining a node as a child of DjangoNode result in install_labels being called before the app is initialized with project settings, causing the connection to fail if you have changed the neo4j user or password. See the following stack trace:

```
Traceback (most recent call last):
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/media/pawantu/Data/git/omnidia/neograph/models.py", line 11, in <module>
    class Dataset(DjangoNode):
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neomodel/core.py", line 104, in __new__
    install_labels(inst)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neomodel/core.py", line 42, in install_labels
    cls.__label__, key))
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neomodel/util.py", line 27, in wrapper
    self.set_connection(config.DATABASE_URL)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neomodel/util.py", line 60, in set_connection
    self.refresh_connection()
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neomodel/util.py", line 28, in wrapper
    return func(self, *args, **kwargs)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neomodel/util.py", line 67, in refresh_connection
    self._session = self.driver.session()
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/session.py", line 148, in session
    session = Session(self)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/session.py", line 461, in __init__
    self.connection = connect(driver.host, driver.port, driver.ssl_context, **driver.config)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/connection.py", line 465, in connect
    return Connection(s, der_encoded_server_certificate=der_encoded_server_certificate, **config)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/connection.py", line 237, in __init__
    self.fetch()
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/connection.py", line 326, in fetch
    self.acknowledge_failure()
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/connection.py", line 273, in acknowledge_failure
    fetch()
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/connection.py", line 311, in fetch
    raw.writelines(self.channel.chunk_reader())
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/connection.py", line 169, in chunk_reader
    chunk_header = self._recv(2)
  File "/media/pawantu/Data/isolated/virtualenvs/omnidia/lib/python3.5/site-packages/neo4j/v1/connection.py", line 152, in _recv
    raise ProtocolError("Server closed connection")
neo4j.v1.exceptions.ProtocolError: Server closed connection
```

**Comment by robinedwards** [comment]
Hmm i have just tried to reproduce this and i am struggling to. 

Have you got django_neomodel in your installed apps before any of your local apps? It needs to come before them in the list. 

I am guessing you haven't set AUTO_INSTALL_LABELS to true somewhere?

Perhaps you could push an example to a repo or a snippet to reproduce somewhere.

**Comment by Pawamoy** [comment]
Hmmm okay I put django_neomodel above other apps and it works now

**Comment by robinedwards** [comment]
Super, I am going to try and catch this some how and display a friendly
message in the future.

**Comment by robinedwards** [comment]
Right neomodel 3.2.0 will no longer calls install_labels at compile time. It's not released yet but has been pushed to master
