### ISSUE TITLE
strange error after following guideline

### ISSUE THREAD

**Issue by samdeleu** [robinedwards/django-neomodel#3]
Hi,

I was trying to get the module for django/neo4j up but i encountered the following message:
Do you have an idea what went wrong?

$ python
Python 3.6.0 (default, Mar 23 2017, 13:21:20) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(portal_neo4j) 
samdeleu at Sam.local in ~/.../Mind4Energy/portal_neo4j/p1
$ python manage.py install_labels
Setting up indexes and constraints...

Found django_neomodel.DjangoNode
 ! Skipping class django_neomodel.DjangoNode is abstract
Found p1a.models.Book
 + Creating unique constraint for title on label Book for class p1a.models.Book
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/django_neomodel/management/commands/install_labels.py", line 12, in handle
    install_all_labels(stdout=self.stdout)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neomodel/core.py", line 70, in install_all_labels
    install_labels(cls, quiet=False, stdout=stdout)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neomodel/core.py", line 47, in install_labels
    cls.__label__, key))
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neomodel/util.py", line 27, in wrapper
    self.set_connection(config.DATABASE_URL)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neomodel/util.py", line 63, in set_connection
    self.refresh_connection()
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neomodel/util.py", line 28, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neomodel/util.py", line 70, in refresh_connection
    self._session = self.driver.session()
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/v1/bolt.py", line 51, in session
    return BoltSession(self.pool.acquire(self.address))
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 459, in acquire
    connection = self.connector(address)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/v1/bolt.py", line 46, in <lambda>
    pool = ConnectionPool(lambda a: connect(a, security_plan.ssl_context, **config))
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 615, in connect
    return Connection(s, der_encoded_server_certificate=der_encoded_server_certificate, **config)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 256, in __init__
    self.buffering_socket = BufferingSocket(self)
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 99, in __init__
    self.address = Address(*self.socket.getpeername())
TypeError: __new__() takes 3 positional arguments but 5 were given
Exception ignored in: <bound method Connection.__del__ of <neo4j.bolt.connection.Connection object at 0x1074373c8>>
Traceback (most recent call last):
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 289, in __del__
    self.close()
  File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/lib/python3.6/site-packages/neo4j/bolt/connection.py", line 419, in close
    self.channel.socket.close()
AttributeError: 'Connection' object has no attribute 'channel'
(portal_neo4j)

**Comment by robinedwards** [comment]
Hey,

Apologies that's not the most friendly error messages!

It looks like it could be a connection issue. The trace is actually coming
from neo4j driver but this can happen when something goes wrong further up
the stack.

Have you confirmed the connection to neo4j works from django by issuing a
simple cypher command? db.cypher_query()

R


On 20 Apr 2017 01:24, "Sam Deleu" <notifications@github.com> wrote:

Hi,

I was trying to get the module for django/neo4j up but i encountered the
following message:
Do you have an idea what went wrong?

$ python
Python 3.6.0 (default, Mar 23 2017, 13:21:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

exit()
(portal_neo4j)
samdeleu at Sam.local in ~/.../Mind4Energy/portal_neo4j/p1
$ python manage.py install_labels
Setting up indexes and constraints...

Found django_neomodel.DjangoNode
! Skipping class django_neomodel.DjangoNode is abstract
Found p1a.models.Book

   - Creating unique constraint for title on label Book for class
   p1a.models.Book
   Traceback (most recent call last):
   File "manage.py", line 22, in
   execute_from_command_line(sys.argv)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/django/core/management/*init*.py", line 363,
   in execute_from_command_line
   utility.execute()
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/django/core/management/*init*.py", line 355,
   in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/django/core/management/base.py", line 283, in
   run_from_argv
   self.execute(*args, **cmd_options)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/django/core/management/base.py", line 330, in
   execute
   output = self.handle(*args, **options)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/django_neomodel/management/commands/install_labels.py",
   line 12, in handle
   install_all_labels(stdout=self.stdout)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neomodel/core.py", line 70, in
   install_all_labels
   install_labels(cls, quiet=False, stdout=stdout)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neomodel/core.py", line 47, in install_labels
   cls.*label*, key))
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neomodel/util.py", line 27, in wrapper
   self.set_connection(config.DATABASE_URL)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neomodel/util.py", line 63, in set_connection
   self.refresh_connection()
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neomodel/util.py", line 28, in wrapper
   return func(self, *args, **kwargs)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neomodel/util.py", line 70, in
   refresh_connection
   self._session = self.driver.session()
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/v1/bolt.py", line 51, in session
   return BoltSession(self.pool.acquire(self.address))
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/bolt/connection.py", line 459, in
   acquire
   connection = self.connector(address)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/v1/bolt.py", line 46, in
   pool = ConnectionPool(lambda a: connect(a, security_plan.ssl_context,
   **config))
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/bolt/connection.py", line 615, in
   connect
   return Connection(s,
der_encoded_server_certificate=der_encoded_server_certificate,
   **config)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/bolt/connection.py", line 256, in *init*
   self.buffering_socket = BufferingSocket(self)
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/bolt/connection.py", line 99, in *init*
   self.address = Address(*self.socket.getpeername())
   TypeError: *new*() takes 3 positional arguments but 5 were given
   Exception ignored in: <bound method Connection.*del* of
   <neo4j.bolt.connection.Connection object at 0x1074373c8>>
   Traceback (most recent call last):
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/bolt/connection.py", line 289, in *del*
   self.close()
   File "/Users/samdeleu/Repositories/Git/Mind4Energy/portal_neo4j/l
   ib/python3.6/site-packages/neo4j/bolt/connection.py", line 419, in close
   self.channel.socket.close()
   AttributeError: 'Connection' object has no attribute 'channel'
   (portal_neo4j)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robinedwards/django-neomodel/issues/3>, or mute the
thread

**Comment by samdeleu** [comment]
Hi,

I re-installed the neo-driver and then it worked.
After upgrading the django-neomodel to version 0.0.3, neomodel 3.2.3, the same strange error occurred.
a pip install neo4j-driver --upgrade resolved the issue once again.

Apparently there is some strange dependency, but i couldnt figure out what it was exactly.

Sam
