### ISSUE TITLE
ValidationError on ModelForms with excluded fields

### ISSUE THREAD

**Issue by aaronst** [robinedwards/django-neomodel#6]
I think there is a bug in the way `django_neomodel` and/or `neomodel` tries to validate `ModelForm`s for `DjangoNode`s.  I have a `DjangoNode` with some required fields and, through `neomodel` (not through a Django `ModelForm`), created an instance of it.  I then created a `ModelForm` to update a subset of the fields, excluding some of the required fields.  When I try to submit this form, I get `neomodel.exception.RequiredProperty`, which causes `django.core.exceptions.ValidationError`, which causes `ValueError`.  It tells me that one of the required properties is required, and it complains that I do not have it included in the `ModelForm`.

At `django_neomodel/__init__.py`, in `DjangoNode`'s `full_clean()` method, the required fields that I did not include in my `ModelForm` are removed from the list of properties to be validated before calling `deflate()`.

At `neomodel/properties.py`, in `PropertyManager`'s `deflate()` method, the full list of properties is pulled from the `DjangoNode` to validate the properties provided by `full_clean()`.  Iterating through the full list of properties, it soon lands on one of the required properties that was not included in the `ModelForm` and raises the `neomodel.exception.RequiredProperty`.

I'm not exactly sure where the change needs to be happen, but I'm pretty certain this is a bug.

**Comment by robinedwards** [comment]
Thanks for the report.

So just to confirm you're trying to update a subset of the properties via a
MF. A neomodel  required property is not present in the form (as you don't
want to update it)  and you are getting a ValueError from django_neomodel
code because it is missing?

R

**Comment by aaronst** [comment]
Yep that's correct.  Would providing code snippets help?

**Comment by robinedwards** [comment]
Yes please that would be great!

**Comment by aaronst** [comment]
Here are the relevant parts of the `DjangoNode`, the classes get quite big with all of the methods and relationships.

```python
class STIXObjectMixin:

    # Properties

    stype = StringProperty(required=True)

    sid = StringProperty(unique_index=True, required=True)

    created = DateTimeProperty(required=True)

    modified = DateTimeProperty(required=True)

    revoked = BooleanProperty(default=False)

    confidence = IntegerProperty()

    lang = StringProperty()

    external_references = ArrayProperty(JSONProperty())

    granular_markings = ArrayProperty(JSONProperty())


class STIXDomainObject(DjangoNode, STIXObjectMixin):

    __abstract_node__ = True

    class Meta:
        app_label = 'graph'


class ThreatActor(STIXDomainObject):

    # Properties

    labels = ArrayProperty(StringProperty(choices=threat_actor_label_ov),
                           required=True)

    name = StringProperty(index=True, required=True)

    description = StringProperty()

    aliases = ArrayProperty(StringProperty())

    roles = ArrayProperty(StringProperty(choices=threat_actor_role_ov))

    goals = ArrayProperty(StringProperty())

    sophistication = StringProperty(choices=threat_actor_sophistication_ov)

    resource_level = StringProperty(choices=attack_resource_level_ov)

    primary_motivation = StringProperty(choices=attack_motivation_ov)

    secondary_motivations = ArrayProperty(
        StringProperty(choices=attack_motivation_ov)
    )

    personal_motivations = ArrayProperty(
        StringProperty(choices=attack_motivation_ov)
    )

```

Here is the `ModelForm`.

```python
class ListField(Field):
    """Field to submit an arbitrary list of strings."""

    widget = Textarea

    def __init__(self, empty_value=None, *args, **kwargs):
        """Basic `__init__()`."""

        self.empty_value = empty_value

        super(ListField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        """Convert string to list of strings."""

        if value in self.empty_values:
            return self.empty_value

        return sub(r'[\[\]\s]', '', force_text(value)).split(',')


class ThreatActorForm(ModelForm):
    """Form for `ThreatActor` nodes."""

    labels = TypedMultipleChoiceField(
        choices=threat_actor_label_ov, required=True, coerce=list,
        widget=SelectMultiple(attrs={'style': 'height:100px'}), label='labels')

    roles = TypedMultipleChoiceField(
        choices=threat_actor_role_ov, required=False, coerce=list,
        widget=SelectMultiple(attrs={'style': 'height:100px'}), label='roles')

    s_choices = list(threat_actor_sophistication_ov)
    s_choices.append(('', ''))

    sophistication = TypedChoiceField(choices=s_choices, required=False,
                                      empty_value=None, coerce=str)

    rl_choices = list(attack_resource_level_ov)
    rl_choices.append(('', ''))

    resource_level = TypedChoiceField(choices=rl_choices, required=False,
                                      empty_value=None, coerce=str)

    pm_choices = list(attack_motivation_ov)
    pm_choices.append(('', ''))

    primary_motivation = TypedChoiceField(choices=pm_choices, required=False,
                                          empty_value=None, coerce=str)

    external_references = ListField(label='external_references')

    granular_markings = ListField(label='granular_markings')

    aliases = ListField(label='aliases')

    goals = ListField(label='goals')

    class Meta:
        model = ThreatActor

        fields = ['revoked', 'confidence', 'external_references', 'lang',
                  'granular_markings', 'labels', 'name', 'description',
                  'aliases', 'roles', 'goals', 'sophistication',
                  'resource_level', 'primary_motivation',
                  'secondary_motivations', 'personal_motivations']

        labels = {
            'revoked': 'revoked',
            'confidence': 'confidence',
            'lang': 'lang',
            'granular_markings': 'granular_markings',
            'name': 'name',
            'description': 'description',
            'aliases': 'aliases',
            'goals': 'goals',
            'sophistication': 'sophistication',
            'resource_level': 'resource_level',
            'primary_motivation': 'primary_motivation',
            'secondary_motivations': 'secondary_motivations',
            'personal_motivations': 'personal_motivations'
        }

        widgets = {
            'description': Textarea,
            'secondary_motivations': SelectMultiple(
                attrs={'style': 'height:100px'}, choices=attack_motivation_ov),
            'personal_motivations': SelectMultiple(
                attrs={'style': 'height:100px'}, choices=attack_motivation_ov)
        }
```

Nothing special about the view.

```python
def save(request, sid):
    """Handle POSTs to save graph changes."""

    if request.method == 'POST':
        form = get_form(sid, data=request.POST)

        if form.is_valid():
            form.save()

            n = form.instance.to_vis_json()[0]
            return HttpResponse(str(n))

        return HttpResponse(str(form.errors))
```

And finally, the traceback.  Truncated the paths for privacy.

```
Traceback (most recent call last):
  File "/venv/lib/python3.4/site-packages/django_neomodel/__init__.py", line 166, in full_clean
    self.deflate(props, self)
  File "/venv/lib/python3.4/site-packages/neomodel/properties.py", line 85, in deflate
    raise RequiredProperty(key, cls)
neomodel.exception.RequiredProperty: property 'stype' on objects of class ThreatActor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.4/site-packages/django/forms/models.py", line 396, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/venv/lib/python3.4/site-packages/django_neomodel/__init__.py", line 170, in full_clean
    raise ValidationError({e.property_name: 'is required'})
django.core.exceptions.ValidationError: {'stype': ['is required']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.4/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/views.py", line 37, in save
    if form.is_valid():
  File "/venv/lib/python3.4/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/venv/lib/python3.4/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/venv/lib/python3.4/site-packages/django/forms/forms.py", line 386, in full_clean
    self._post_clean()
  File "/venv/lib/python3.4/site-packages/django/forms/models.py", line 398, in _post_clean
    self._update_errors(e)
  File "/venv/lib/python3.4/site-packages/django/forms/models.py", line 372, in _update_errors
    self.add_error(None, errors)
  File "/venv/lib/python3.4/site-packages/django/forms/forms.py", line 352, in add_error
    "'%s' has no field named '%s'." % (self.__class__.__name__, field))
ValueError: 'ThreatActorForm' has no field named 'stype'.
```

**Comment by aaronst** [comment]
@robinedwards gotten a chance to look into this yet?
