### ISSUE TITLE
DjangoNode's post_save AttributeError: no attribute '_creating_node'

### ISSUE THREAD

**Issue by aaronst** [robinedwards/django-neomodel#9]
Getting the following error when attempting to update a `DjangoNode` via a `Form`s `save()` method.

```
Traceback (most recent call last):
  File "/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/views.py", line 38, in save
    form.save()
  File "/django/forms/models.py", line 451, in save
    self.instance.save()
  File "/neomodel/hooks.py", line 11, in hooked
    _exec_hook('post_' + fn_name, self)
  File "/neomodel/hooks.py", line 3, in _exec_hook
    getattr(self, hook_name)()
  File "/django_neomodel/__init__.py", line 193, in post_save
    created = self._creating_node
AttributeError: '<name_of_DjangoNode>' object has no attribute '_creating_node'

**Comment by aaronst** [comment]
For clarity, I'm using the same `DjangoNode` and `Form` as I was in #6.

**Comment by robinedwards** [comment]
Sorry is this the stock django_neomodel DjangoNode from django_neomodel
0.0.4 (the latest)?

If so can you provide a minimal snippet to recreate the issue

**Comment by aaronst** [comment]
I'm confused as to how this happening, because in `DjangoNode`s `pre_save()`, the `_creating_node` attribute is set to a boolean.

```python
def pre_save(self):
    if getattr(settings, 'NEOMODEL_SIGNALS', True):
        self._creating_node = getattr(self, 'id', None) is None
        signals.pre_save.send(sender=self.__class__, instance=self)
```

**Comment by robinedwards** [comment]
Are you overriding pre_save() somewhere and not calling super? It would be
helpful to have an minimal snippet, i,e 10 lines without all the noise.

**Comment by aaronst** [comment]
Doh!  You're right.  I'm not calling super.  Sorry!
